[package]
name = "aoc-2024"
version = "0.1.0"
edition = "2021"

[dependencies]
bmp = "0.5.0"
clap = { version = "4.5.21", features = ["derive"] }
ilog = "1.0.1"
itertools = "0.13.0"
rayon = "1.10.0"
regex = "1.11.1"

[profile.release]
lto = true
